### PR TITLE
style: update screenshots

### PR DESCRIPTION
**Pull request by yajo**
Fix https://github.com/flathub/us.zoom.Zoom/issues/295.

### CODE REVIEW

**Comment by nedrichards** [comment]
If we're going to have non 'hosted on the upstream website' screenshots for an app like this then I think we need them in this repo as well since if they go away they will do very annoying things to builds, websites and app stores.

**Comment by yajo** [comment]
The links are borrowed from this comment: https://github.com/flathub/us.zoom.Zoom/issues/295#issue-1051344536

I've never seen github to delete images attached to a comment. Do you really think that is necessary?

**Comment by camelCaseNick** [comment]
@yajo They are hosted upstream: https://explore.zoom.us/media/img-modernizemeeting_69f1e3a.png and https://explore.zoom.us/media/zfh-presentation.png.

**Comment by violetmage** [comment]
bump

Can someone merge this?

**Comment by muelli** [comment]
yeah.
(External) Screenshots tend to be a liability because it's a pain when they go away, but we currently have only one screenshot and I think the addition is warranted.
Thanks!

**Pull request merged**
