### PR TITLE
Prevent QT_QPA_PLATFORM from leaking

### LINKED ISSUE #57: Zoom failing to start in Wayland sessions
Zoom doesn't start for me when using Wayland with this error:

```
ZoomLauncher started.
cmd line: 
CreateReportChannel bp_server_fd=4
$HOME = /home/rasmus 
Can't load/home/rasmus/.config/zoomus.conf
export SSB_HOME=/home/rasmus/.zoom; export QSG_INFO=1; export LD_LIBRARY_PATH=/app/extra/zoom; export BREAKPAD_CLIENT_FD=3; /app/extra/zoom/zoom "" 
No PulseAudio daemon running, or not running as session daemon.
zoom started.
Client: Breakpad is using Client-Server Mode! client fd = 3
Could not initialize GLX
sh: line 1:     8 Aborted                 (core dumped) /app/extra/zoom/zoom ""
success to create child process,status is 34304.
zoom exited normally.
Something went wrong while running zoom,exit code is 134.
ZoomLauncher exit.
```

Running on Alpine Linux, with an AMD GPU

### PR DESCRIPTION
**Pull request by nanonyme**
Fixes #57

### CODE REVIEW

**Comment by prometheanfire** [comment]
I wouldn't quite say that this fixes #24 as a fix would be to build/link against wayland (a newer qt would be good too, with that you can set `QT_QPA_PLATFORM='wayland-egl,xcb'` and it will fall back to xcb.  (this doesn't even get into screen sharing via wayland, for that look at xdg-desktop-portal)

It does make zoom easier to launch though.

**Comment by nanonyme** [comment]
Edited the reference away

**Comment by alatiera** [comment]
I am sure its wise to allow the app to use a wayland backnend when the app upstream doesn't test that or claim its supported. Afterall half of its features like screensharing can't possibly work under wayland yet.

**Comment by nanonyme** [comment]
@alatiera well, that is out of scope for this PR anyway. I just want to prevent host variable leaking since it invokes code paths that do not work within the sandbox.

**Comment by alatiera** [comment]
@nanonyme yes, I was replying to the  previous comment about `QT_QPA_PLATFORM='wayland-egl,xcb'`

**Comment by prometheanfire** [comment]
Oh, that'd need upstream to support wayland (the qt libs they link against need updating).  I have newer qt here (system lib wise), so unless you did some more major surgery on this package I don't think it's possible to just add `libQt5WaylandCompositor.so` and `libQt5WaylandClient.so` and just expect it to work.

**Pull request merged**
