### PR TITLE
Combines 2 PRs, to get Wayland share working

### LINKED ISSUE #18: Why does Zoom need full rw access to my home directory?
* https://github.com/flathub/us.zoom.Zoom/blob/f3304a999cef2b9c4c7c6d3f590f671d4ed842b3/us.zoom.Zoom.json#L13

I am new user to Zoom, my organisation decided to require it for remote attendance and I was happy to see it in Flathub. However the filesystem access hit my eyes and I don't see why it wants that wide filesystem access. Could it work with less access?

### PR DESCRIPTION
**Pull request by dac73**
Combines #182, #143, adds update if conf already exists (need to test).
Closes #18, #22

### CODE REVIEW

**Comment by dac73** [comment]
Tested the install, looks fine.

**Comment by kaj** [comment]
I tried `https://dl.flathub.org/build-repo/20637/us.zoom.Zoom.flatpakref`, and it did enable sharing a whiteboard, but not a window or desktop.

I'm using gnome / wayland on Fedora 32.

**Comment by dac73** [comment]
@kaj can you check which permissions does zoom have after install?
On Gnome you can find them in settings, if not on Gnome then you can use https://flathub.org/apps/details/com.github.tchx84.Flatseal

Thanks.

**Comment by kaj** [comment]
@dac73 , according to gnome settings, it seems to have full access to /dev and network as built-in unchangeable permessions, and notifications and running in background are enabled as integration (sorry about the wording, my gnome is in Swedish, so the english words here are just my attempts at translation).

But I'm not really sure the above is about the testing version, it might be remains from the "official" flatpak version (which I had installed earlier but uninstalled for this experiment).

When installing the flatpak, it said:
```
us.zoom.Zoom permissions:
    ipc          network              pulseaudio           x11
    devices      file access [1]      dbus access [2]      bus ownership [3]

    [1] xdg-documents, xdg-videos
    [2] org.freedesktop.PowerManagement.Inhibit, org.freedesktop.ScreenSaver,
        org.gnome.SessionManager, org.gnome.Shell, org.gnome.Shell.Screenshot
    [3] org.kde.*
```

**Comment by dac73** [comment]
Sounds about right. For me it worked when I manually added permissions
`override --talk-name=org.gnome.Shell --talk-name=org.gnome.Shell.Screenshot --talk-name=org.gnome.SessionManager --talk-name=org.freedesktop.PowerManagement.Inhibit --talk-name=org.freedesktop.ScreenSaver us.zoom.Zoom`. So it should work for you too. Can you run it from terminal and check output there, maybe there will be some kined of recognizable error.

**Comment by kaj** [comment]
Lots of output in terminal when I start zoom:

```
ZoomLauncher started.
cmd line: 
CreateReportChannel bp_server_fd=4
$HOME = /home/kaj 
Can't load/home/kaj/.config/zoomus.conf
export SSB_HOME=/home/kaj/.zoom; export QSG_INFO=1; export LD_LIBRARY_PATH=/app/extra/zoom; export BREAKPAD_CLIENT_FD=3; /app/extra/zoom/zoom "" 
No PulseAudio daemon running, or not running as session daemon.
zoom started.
Client: Breakpad is using Client-Server Mode! client fd = 3
[CZPClientLogMgr::LogClientEnvironment] [MacAddr: 9C:B6:D0:8D:29:45][client: Linux][OS: Freedesktop.org 19.08.11 (Flatpak runtime)][Hardware: CPU Core:8 Frenquency:3 G Memory size:15724MB CPU Brand:Intel(R) Core(TM) i7-8705G CPU @ 3.10GHz GPU Brand:][Req ID: ]
Linux Client Version is 5.0.418682.0603
QSG_RENDER_LOOP is 
XDG_CURRENT_DESKTOP = GNOME;   GDMSESSION = gnome
Graphics Card Info:: 00:02.0 VGA compatible controller: Intel Corporation Device 591b (rev 04)
Zoom package arch is 64bit, runing OS arch is x86_64
AppIconMgr::systemDesktopName log Desktop Name: gnome 
qt.scenegraph.general: QSG: basic render loop
qt.scenegraph.general: Using sg animation driver
qt.svg: link image0 hasn't been detected!
qt.svg: :/images/wechat.svg:10:6: Could not resolve property: pattern0
qt.scenegraph.general: texture atlas dimensions: 1024x512
qt.scenegraph.general: R/G/B/A Buffers:    8 8 8 8
qt.scenegraph.general: Depth Buffer:       24
qt.scenegraph.general: Stencil Buffer:     8
qt.scenegraph.general: Samples:            -1
qt.scenegraph.general: GL_VENDOR:          Intel
qt.scenegraph.general: GL_RENDERER:        Mesa Intel(R) HD Graphics 630 (KBL GT2)
qt.scenegraph.general: GL_VERSION:         4.6 (Compatibility Profile) Mesa 20.0.1
qt.scenegraph.general: GL_EXTENSIONS:      GL_ARB_draw_buffers_blend GL_EXT_texture3D GL_KHR_parallel_shader_compile GL_AMD_shader_stencil_export GL_ARB_vertex_shader GL_ARB_shader_atomic_counter_ops GL_ARB_vertex_array_object GL_EXT_texture_edge_clamp GL_ARB_explicit_uniform_location GL_EXT_framebuffer_blit GL_EXT_provoking_vertex GL_ARB_shader_stencil_export GL_ARB_window_pos GL_NV_texture_env_combine4 GL_EXT_draw_instanced GL_ARB_fragment_shader GL_MESA_shader_integer_functions GL_EXT_texture_sRGB GL_ARB_texture_env_crossbar GL_ARB_texture_compression_bptc GL_NV_fragment_shader_interlock GL_MESA_window_pos GL_ARB_gpu_shader_int64 GL_ARB_fragment_shader_interlock GL_EXT_shader_framebuffer_fetch GL_ARB_query_buffer_object GL_NV_packed_depth_stencil GL_ARB_parallel_shader_compile GL_EXT_texture_object GL_EXT_texture_integer GL_ARB_spirv_extensions GL_ARB_blend_func_extended GL_ARB_sync GL_INTEL_shader_atomic_float_minmax GL_EXT_point_parameters GL_AMD_performance_monitor GL_EXT_pixel_buffer_object GL_ARB_buffer_storage GL_ARB_transform_feedback3 GL_AMD_texture_texture4 GL_MESA_framebuffer_flip_y GL_NV_fog_distance GL_ARB_shader_bit_encoding GL_ARB_texture_compression_rgtc GL_ARB_ES3_compatibility GL_ARB_texture_mirrored_repeat GL_ARB_occlusion_query2 GL_ARB_program_interface_query GL_OES_EGL_image GL_ARB_shader_viewport_layer_array GL_ARB_shadow GL_ARB_get_texture_sub_image GL_ARB_internalformat_query2 GL_ARB_transform_feedback_overflow_query GL_ARB_separate_shader_objects GL_ARB_cull_distance GL_ANGLE_texture_compression_dxt5 GL_EXT_draw_range_elements GL_EXT_texture_rectangle GL_ATI_blend_equation_separate GL_KHR_robustness GL_EXT_texture_compression_dxt1 GL_ARB_texture_buffer_range GL_AMD_shader_trinary_minmax GL_EXT_framebuffer_multisample GL_ARB_enhanced_layouts GL_ARB_draw_instanced GL_EXT_vertex_attrib_64bit GL_ARB_texture_cube_map_array GL_ARB_explicit_attrib_location GL_ARB_transpose_matrix GL_ARB_texture_view GL_KHR_context_flush_control GL_EXT_texture_sRGB_R8 GL_ARB_tessellation_shader GL_EXT_framebuffer_multisample_blit_scaled GL_ARB_clear_texture GL_KHR_texture_compression_astc_ldr GL_EXT_texture_env_add GL_AMD_depth_clamp_separate GL_ANGLE_texture_compression_dxt3 GL_ARB_vertex_attrib_binding GL_ARB_shading_language_420pack GL_ARB_sample_shading GL_IBM_texture_mirrored_repeat GL_EXT_texture_array GL_ARB_gl_spirv GL_ARB_provoking_vertex GL_ARB_point_sprite GL_EXT_shader_samples_identical GL_NV_compute_shader_derivatives GL_ARB_multi_draw_indirect GL_EXT_subtexture GL_ARB_framebuffer_sRGB GL_EXT_fog_coord GL_ARB_conditional_render_inverted GL_INGR_blend_func_separate GL_NV_conditional_render GL_ARB_texture_buffer_object_rgb32 GL_KHR_texture_compression_astc_sliced_3d GL_ARB_shader_atomic_counters GL_EXT_texture GL_ARB_multisample GL_EXT_copy_texture GL_NV_texgen_reflection GL_EXT_texture_cube_map GL_ARB_fragment_coord_conventions GL_ARB_multitexture GL_EXT_vertex_array GL_ARB_invalidate_subdata GL_EXT_packed_depth_stencil GL_NV_depth_clamp GL_ATI_texture_float GL_EXT_stencil_wrap GL_ARB_fragment_program_shadow GL_EXT_timer_query GL_EXT_packed_pixels GL_ARB_texture_env_combine GL_ARB_instanced_arrays GL_ARB_texture_storage_multisample GL_EXT_texture_env_dot3 GL_ARB_texture_border_clamp GL_ARB_compressed_texture_pixel_storage GL_ARB_map_buffer_range GL_EXT_abgr GL_ARB_depth_clamp GL_ARB_robust_buffer_access_behavior GL_NV_light_max_exponent GL_EXT_bgra GL_ARB_fragment_program GL_EXT_texture_buffer_object GL_EXT_rescale_normal GL_ARB_depth_buffer_float GL_SGIS_texture_edge_clamp GL_IBM_rasterpos_clip GL_ARB_draw_buffers GL_ARB_shader_texture_lod GL_ARB_copy_image GL_KHR_debug GL_KHR_robust_buffer_access_behavior GL_ARB_vertex_array_bgra GL_INTEL_performance_query GL_ARB_shading_language_include GL_ARB_vertex_buffer_object GL_ARB_texture_rg GL_ARB_texture_storage GL_ARB_gpu_shader_fp64 GL_AMD_draw_buffers_blend GL_EXT_framebuffer_object GL_ARB_multi_bind GL_ARB_direct_state_access GL_ARB_half_float_pixel GL_EXT_texture_env_combine GL_AMD_vertex_shader_viewport_index GL_ARB_compatibility GL_ARB_texture_gather GL_ARB_gpu_shader5 GL_ARB_pipeline_statistics_query GL_ATI_texture_env_combine3 GL_INTEL_shader_integer_functions2 GL_MESA_texture_signed_rgba GL_ARB_texture_query_levels GL_ARB_texture_non_power_of_two GL_ARB_draw_elements_base_vertex GL_MESA_pack_invert GL_ARB_arrays_of_arrays GL_EXT_blend_color GL_SGIS_texture_border_clamp GL_ARB_texture_multisample GL_EXT_texture_filter_anisotropic GL_ARB_clip_control GL_ARB_debug_output GL_ARB_conservative_depth GL_ARB_ES2_compatibility GL_ARB_depth_texture GL_ARB_viewport_array GL_ARB_shader_texture_image_samples GL_ARB_clear_buffer_object GL_EXT_compiled_vertex_array GL_ARB_shader_draw_parameters GL_EXT_secondary_color GL_EXT_vertex_array_bgra GL_ARB_texture_compression GL_NV_blend_square GL_ARB_map_buffer_alignment GL_ARB_fragment_layer_viewport GL_ARB_seamless_cube_map GL_EXT_shader_integer_mix GL_ARB_occlusion_query GL_SUN_multi_draw_arrays GL_ARB_get_program_binary GL_EXT_texture_shared_exponent GL_EXT_blend_func_separate GL_EXT_gpu_shader4 GL_EXT_packed_float GL_ARB_timer_query GL_ARB_framebuffer_no_attachments GL_ARB_ES3_1_compatibility GL_ARB_sampler_objects GL_ARB_post_depth_coverage GL_ARB_base_instance GL_EXT_texture_lod_bias GL_ARB_texture_barrier GL_EXT_demote_to_helper_invocation GL_KHR_blend_equation_advanced_coherent GL_ARB_seamless_cubemap_per_texture GL_EXT_texture_compression_s3tc GL_ARB_vertex_attrib_64bit GL_ARB_texture_env_dot3 GL_KHR_blend_equation_advanced GL_EXT_multi_draw_arrays GL_ARB_stencil_texturing GL_AMD_conservative_depth GL_ARB_texture_query_lod GL_EXT_shader_framebuffer_fetch_non_coherent GL_ARB_color_buffer_float GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_rgb10_a2ui GL_ARB_vertex_program GL_ARB_texture_filter_anisotropic GL_SGIS_generate_mipmap GL_ARB_texture_buffer_object GL_NV_primitive_restart GL_EXT_transform_feedback GL_EXT_stencil_two_side GL_ARB_shader_image_load_store GL_APPLE_packed_pixels GL_ARB_compute_shader GL_ARB_pixel_buffer_object GL_3DFX_texture_compression_FXT1 GL_AMD_query_buffer_object GL_ARB_indirect_parameters GL_ARB_vertex_type_10f_11f_11f_rev GL_EXT_texture_sRGB_decode GL_ATI_separate_stencil GL_AMD_multi_draw_indirect GL_EXT_texture_swizzle GL_ARB_shader_subroutine GL_ARB_internalformat_query GL_ARB_shader_group_vote GL_IBM_multimode_draw_arrays GL_AMD_seamless_cubemap_per_texture GL_ARB_texture_float GL_EXT_draw_buffers2 GL_ARB_shader_image_size GL_ARB_half_float_vertex GL_ARB_draw_indirect GL_ARB_texture_swizzle GL_EXT_gpu_program_parameters GL_ARB_derivative_control GL_ARB_texture_env_add GL_EXT_blend_subtract GL_EXT_polygon_offset_clamp GL_EXT_texture_shadow_lod GL_ARB_copy_buffer GL_AMD_vertex_shader_layer GL_ARB_shader_storage_buffer_object GL_AMD_pinned_memory GL_ARB_framebuffer_object GL_EXT_texture_snorm GL_ATI_draw_buffers GL_ARB_shader_clock GL_ARB_uniform_buffer_object GL_EXT_framebuffer_sRGB GL_EXT_EGL_sync GL_ARB_transform_feedback_instanced GL_ARB_point_parameters GL_EXT_EGL_image_storage GL_EXT_shadow_funcs GL_KHR_no_error GL_SGIS_texture_lod GL_NV_texture_rectangle GL_ATI_fragment_shader GL_ARB_shading_language_packing GL_ARB_texture_stencil8 GL_ARB_texture_cube_map GL_ARB_vertex_type_2_10_10_10_rev GL_NV_texture_barrier GL_ARB_texture_rectangle GL_ARB_robustness GL_ARB_shader_ballot GL_S3_s3tc GL_EXT_texture_compression_rgtc GL_EXT_separate_specular_color GL_ARB_shading_language_100 GL_ARB_shader_precision GL_EXT_blend_minmax GL_OES_read_format GL_ARB_transform_feedback2 GL_ARB_polygon_offset_clamp GL_EXT_blend_equation_separate GL_ARB_shader_objects GL_EXT_direct_state_access
qt.scenegraph.general: Max Texture Size:  16384
qt.scenegraph.general: Debug context:     false
Error: Send error, 22 Ogiltigt argument
Error: Send error, 22 Ogiltigt argument
Error: Send error, 22 Ogiltigt argument
```

Then the following line when I enter a room:
```
CSBConfUI::OnConfStatusChanged  UI_CMD_SHARE_READY
```

And no more output when I click share screen, but the selector window only contains the Whiteboard.

(and all this is after running the `flatpak override` command).

**Comment by dac73** [comment]
We need more people testing this, it worked for me on F32:Gnome:Wayland :man_shrugging:

**Comment by sagarchalise** [comment]
I have been testing this build in fedora 32. One odd issue I am facing is not all windows are shared in screen sharing.
When I enable screen sharing seems gtk apps are not shared but others are shared. I haven't checked with flatpak built gtk apps but system gtk apps are not seen at all in the other side. Only `java` based, `electron` based e.g. vscode, `chrome` and flatpak run viber is seen. Otherwise the following screen is seen although I open `firefox`, `evince` etc. Anyone else facing such issues ?

zoom_screenshare

**Comment by ninja-** [comment]
I tried to access the build with flatpak install but it says 404

```
błąd: Can't load uri https://dl.flathub.org/build-repo/20637/us.zoom.Zoom.flatpakref: Server returned status 404: Not Found
```

**Comment by dac73** [comment]
bot, build

**Comment by ninja-** [comment]
right.
So on Ubuntu 20.04 it shows white screen as "Desktop 1". It works fine on the deb version.

**Comment by tenni-paws** [comment]
same
```error: Can't load uri https://dl.flathub.org/build-repo/21251/us.zoom.Zoom.flatpakref: Server returned status 404: Not Found```

bot, build

**Comment by dac73** [comment]
I just tested this, with the latest version and now it's not working.
Not sure what changed.

**Comment by TheEvilSkeleton** [comment]
@dac73 Can you test this one out? https://github.com/flathub/us.zoom.Zoom/pull/199

**Comment by kamalmarhubi** [comment]
bot, build

**Comment by kamalmarhubi** [comment]
@dac73 in case it's useful: I just tried this out, looks like I just get a blank screen. Fedora Silverblue 32, updated today.

**Comment by h33p** [comment]
Zoom seems to now request the screenshot to be saved in `/tmp/zoom/zoom_gs.png`. Allowing filesystem access to `/tmp/zoom` seems to make screenshare work

**Comment by refi64** [comment]
Try setting `TMPDIR=$XDG_RUNTIME_DIR/app/us.zoom.Zoom`, it's a common trick used in other Flatpaks when you need some TMPDIR that's shared with the host or across instances.

**Comment by h33p** [comment]
The directory is very much hardcoded on zoom's side `strings zoom | grep /tmp/zoom/zoom_gs.png` has a match. Thus, gnome will be requested to save the screenshot on /tmp, and zoom will expect to find a screenshot on /tmp

**Comment by refi64** [comment]
Hmm could you then symlink /tmp/zoom to be the mentioned path?

**Comment by TheEvilSkeleton** [comment]
Should I open an MR for that?

**Comment by h33p** [comment]
You could symlink it, but I don't believe it is going to achieve anything meaningful, unless we are able to intercept dbus commands and change the path gnome uses to save the screenshot. I'm not sure if there is such a feature in flatpak? I would imagine some kind of path remapping to the overlayfs. But I feel like it's a bit of a niche to exist yet.

**Comment by kamalmarhubi** [comment]
@dac73 
> We need more people testing this, it worked for me on F32:Gnome:Wayland man_shrugging

Did this include sharing individual windows?

**Comment by dac73** [comment]
@kamalmarhubi nope, only per screen.

**Comment by luis-agm** [comment]
bot, build

**Comment by nanonyme** [comment]
Is there any intent on landing this? We're most likely going to need to make incremental progress towards the goal and having heaps of open MR's with different contents isn't really helpful.

**Comment by ozdreamern** [comment]
Is it still possible to test this?  Does another build need to be run?

**Comment by pothos** [comment]
Adding `/tmp` to the shared paths is not so nice but at least it makes it usable. You can already do these changes with https://flathub.org/apps/details/com.github.tchx84.Flatseal if you need screen sharing right now.

**Comment by kaimast** [comment]
Is there anything this pull request breaks? If not, I agree with nanonyme, it should be merged.

**Comment by kaimast** [comment]
Actually, I just tried this branch and have multiple issues with it. First, for some reason my screen share shows x11 windows. I think Zoom launches under XWayland but not sure why... 

I then purged all zoom config files from my home directory and reinstalled the flatpak. Now I get the following error.

```> flatpak run us.zoom.Zoom/x86_64/master
cp: cannot stat '/app/etc/zoomus.conf': No such file or directory
```
which seems to be caused by this line in the us.zoom.Zoom.json file. 
```
 "test -e $XDG_CONFIG_HOME/zoomus.conf && sed -i 's/enableWaylandShare=false/enableWaylandShare=true/' $XDG_CONFIG_HOME/zoomus.conf || cp /app/etc/zoomus.conf $XDG_CONFIG_HOME/zoomus.conf",
                        "exec env TMPDIR=$XDG_CACHE_HOME /app/extra/zoom/ZoomLauncher \"$@\""
```

**Comment by jmou** [comment]
> I think Zoom launches under XWayland but not sure why...

From what I understand, Zoom is compiled without Wayland support. They are probably the only ones who can fix that. https://github.com/flathub/us.zoom.Zoom/issues/24

**Comment by kaimast** [comment]
> > I think Zoom launches under XWayland but not sure why...
> 
> From what I understand, Zoom is compiled without Wayland support. They are probably the only ones who can fix that. #24

Actually that seems to have changed? Setting `QT_QPA_PLATFORM` to `wayland` or `wayland-egl` makes Zoom run under Wayland (I modified the zoom.sh script [like so](https://github.com/kaimast/us.zoom.Zoom/blob/fix-wayland/zoom.sh)).

Sadly, screen share still does not seem to work for me, it either captures a black screen or crashes. I think something on the Zoom side has changed again...

**Comment by ozdreamern** [comment]
@kaimast Thanks for sharing that.  I was able to launch Zoom as a native Wayland app (based on the changed window decorations and the [xeyes trick](https://medium.com/@bugaevc/how-to-easily-determine-if-an-app-runs-on-xwayland-or-on-wayland-natively-8191b506ab9a)).  I can start a new meeting, select "Share Screen", and it presents me with the option to share my entire desktop, or a whiteboard.  This is exactly the same behaviour as when I launch it under XWayland.  Under XWayland, sharing the desktop "works", partially (the windows that appear to others are the ones also running under XWayland).  Under Wayland, other users see nothing.

On the other hand, under native Wayland, Zoom crashes if I try to join anyone else's meeting (it plays <1 second of the audio stream, loads none of the video elements, then exits).  I can't find any useful logs or errors to help work this out at the moment, so back to XWayland for now.

**Comment by kaimast** [comment]
> On the other hand, under native Wayland, Zoom crashes if I try to join anyone else's meeting (it plays <1 second of the audio stream, loads none of the video elements, then exits). I can't find any useful logs or errors to help work this out at the moment, so back to XWayland for now.

Strange. Regular meetings work fine for me. There are a few glitches with HighDPI and mouse input, but otherwise everything is fine.

I wonder if they are still using gnome's screenshot API for wayland screenshare or something else like pipewire. Looking at the licenses, it seems the have switched from Qt5.6 to Qt5.12, so a bunch of stuff might have changed.

**Comment by TheEvilSkeleton** [comment]
> Actually, I just tried this branch and have multiple issues with it. First, for some reason my screen share shows x11 windows. I think Zoom launches under XWayland but not sure why...

That's normal.

**Comment by TheEvilSkeleton** [comment]
I'm not too sure why this MR is still open. I've already submitted some to get most of the stuff working:
- https://github.com/flathub/us.zoom.Zoom/pull/231
- https://github.com/flathub/us.zoom.Zoom/pull/245

If screen sharing doesn't work in the latest version, then that's just Zoom changing stuff *again*.

I'd like to suggest to submit MRs since the [script](https://github.com/flathub/us.zoom.Zoom/blob/master/zoom.sh) always has room for improvement.

**Comment by kaimast** [comment]
> > Actually, I just tried this branch and have multiple issues with it. First, for some reason my screen share shows x11 windows. I think Zoom launches under XWayland but not sure why...
> 
> That's normal.

I meant it only shows those windows running under XWayland. I cannot actually share any content of wayland clients. 

There is still a crash involving screen recording on wayland so I am not sure if I want to create a merge request for my branch just yet...

**Comment by kaimast** [comment]
I created a new pull request at #255. Let's close this one?

**Comment by dac73** [comment]
This is stale, closing.

**Pull request closed without merging**
