### PR TITLE
Updated Zoom icons and desktop file

### PR DESCRIPTION
**Pull request by msvamp**
Changes are based on files pulled from the latest package v5.3.472687.1012 from https://zoom.us/download
The categories section in the desktop file also contains some additional categories that were added logically based on the [GNOME Desktop Menu Specification](https://developer.gnome.org/menu-spec/#additional-category-registry)

### CODE REVIEW

**Comment by TheEvilSkeleton** [comment]
@msvamp I think you forgot to change the appdata file https://github.com/flathub/us.zoom.Zoom/blob/master/us.zoom.Zoom.appdata.xml#L7

**Comment by msvamp** [comment]
> @msvamp I think you forgot to change the appdata file https://github.com/flathub/us.zoom.Zoom/blob/master/us.zoom.Zoom.appdata.xml#L7

What is the source for the `summary` and `description` sections in the appdata file? Is it sourced somewhere from the Zoom website?

Sorry, I am new to Flathub (and Flatpaks), so don't know a lot about it.

**Comment by TheEvilSkeleton** [comment]
> Is it sourced somewhere from the Zoom website?

Yes, usually it's from the website. I'm not sure exactly where it is 
because Zoom's website is so god damn hard to navigate.

The contents in the appdata file are the stuff you see in the `flatpak 
search` command, in the Flathub website, GNOME Software, etc.

**Comment by msvamp** [comment]
Thanks for the explanation @TheEvilSkeleton!

I'll look through the website soon, and check if there's something worth updating in the `appdata` file.

**Pull request merged**
