### PR TITLE
Enable Wayland support

### PR DESCRIPTION
**Pull request by TheEvilSkeleton**

### CODE REVIEW

**Comment by TheEvilSkeleton** [comment]
I just tested it, and it seems to be working. First startup doesn't do it, but the second startup seems to turn it into `true`, which is what we want.

Unfortunately, the issue will only get fixed if https://github.com/flathub/us.zoom.Zoom/pull/217 gets merged.

**Comment by TheEvilSkeleton** [comment]
@jadahl sorry for the late reply. Unfortunately [many](https://github.com/flathub/us.zoom.Zoom/issues/22) people want screen sharing on Wayland, so it's better to do it OOTB rather than making the user manually allow Zoom to talk to `org.gnome.Shell`. The only solution I found is letting it talk to `org.gnome.Shell`, but is somebody finds the specific bus that Zoom talks to them that would be very helpful.

**Comment by jadahl** [comment]
I can understand people want screencast to work, but it should be made clear that practically no sandboxing is in place this way. Maybe it should be made more obvious by the store UI though, when sandboxing is disabled for certain applications.

**Comment by TheEvilSkeleton** [comment]
You can always suggest changes in the [Flatpak](https://github.com/flatpak/flatpak/issues) repository. I'm not a Flatpak developers so I won't make any magic :(

**Pull request merged**
