### PR TITLE
Improve shell script

### PR DESCRIPTION
**Pull request by TheEvilSkeleton**
- Use double quotes to prevent globbing
- Use tab on a line to improve indentation

### CODE REVIEW

**Comment by muelli** [comment]
Can you make a commit message that describes what you're attempting to achieve?
It currently reads "improving", that's what I always expect of a change, so it doesn't carry any news.

Does your change address an actual problem? Can you show how it becomes one?

**Comment by TheEvilSkeleton** [comment]
It doesn't really fix anything, it just looks prettier and might work better.

I used https://www.shellcheck.net/ to help myself with the script.

**Comment by TheEvilSkeleton** [comment]
Any reason why this hasn't been merged?

**Comment by nedrichards** [comment]
None really, give it a quick rebase and poke me if I don't merge

**Pull request merged**
