### PR TITLE
Remove XDG

### PR DESCRIPTION
**Pull request by TheEvilSkeleton**
Fix https://github.com/flathub/us.zoom.Zoom/issues/208

### CODE REVIEW

**Comment by TheEvilSkeleton** [comment]
@Exalm can you test if it works for you or not?

**Comment by Exalm** [comment]
It's exactly same as the override I did at the time, should work. Cannot check, I don't have access to that computer atm.

**Comment by TheEvilSkeleton** [comment]
Alright, take your time

**Comment by TheEvilSkeleton** [comment]
I'm going to close this because I'm going to PR to the beta repo.

**Pull request closed without merging**
